<?php
declare(strict_types=1);

namespace AzerioidPanel\Broker\Actions;

use AzerioidPanel\Broker\Config;
use AzerioidPanel\Broker\Mail\MailManager;
use AzerioidPanel\Broker\Runtime;

/**
 * mail.mailbox.list · add · passwd · disable · enable · del
 *
 * Passwords arrive on stdin or are generated by the broker; they are never read
 * from argv, and the generated value is returned exactly once.
 */
final class MailMailbox
{
    public function handle(string $action, array $args, array $input, Runtime $runtime, Config $config): array
    {
        $manager = new MailManager($config, $runtime);
        $password = (string) ($input['password'] ?? '');

        return match ($action) {
            'mail.mailbox.list' => $manager->listMailboxes(MailInput::optionalDomain($input['domain'] ?? '')),
            'mail.mailbox.add' => $manager->addMailbox(
                (string) ($args[0] ?? ($input['local_part'] ?? '')),
                (string) ($args[1] ?? ($input['domain'] ?? '')),
                $password
            ),
            'mail.mailbox.passwd' => $manager->resetMailboxPassword(self::address($args, $input), $password),
            'mail.mailbox.disable' => $manager->setMailboxDisabled(self::address($args, $input), true),
            'mail.mailbox.enable' => $manager->setMailboxDisabled(self::address($args, $input), false),
            default => $manager->deleteMailbox(
                self::address($args, $input),
                MailInput::bool($input['drop_mail'] ?? false),
                (string) ($input['confirm'] ?? '')
            ),
        };
    }

    private static function address(array $args, array $input): string
    {
        return (string) ($args[0] ?? ($input['address'] ?? ''));
    }
}
