#!/usr/bin/env bash
# Broker binary, sudoers, broker.json with panel_runtime block.
set -euo pipefail

install_broker() {
    echo "==> Installing broker"
    install -d -m 0751 -o root -g root "${PREFIX}"
    install -d -m 0750 -o root -g root "${PREFIX}/src"
    install -d -m 0750 -o root -g root /etc/azerioid-panel
    install -d -m 0770 -o root -g "${WEB_USER}" /var/log/azerioid-panel
    touch /var/log/azerioid-panel/php-fpm.log /var/log/azerioid-panel/auth-fail.log
    chown "${WEB_USER}:${WEB_USER}" /var/log/azerioid-panel/php-fpm.log /var/log/azerioid-panel/auth-fail.log
    chmod 0640 /var/log/azerioid-panel/php-fpm.log /var/log/azerioid-panel/auth-fail.log

    rm -rf "${PREFIX}/src"
    cp -a "${ROOT}/broker/src" "${PREFIX}/src"
    chown -R root:root "${PREFIX}/src"
    chmod -R go-rwx "${PREFIX}/src"
    install -m 0750 -o root -g root "${ROOT}/broker/broker" "${PREFIX}/broker"
    install -m 0640 -o root -g root "${ROOT}/broker/broker.php" "${PREFIX}/broker.php"

    local sudoers=/etc/sudoers.d/azerioid-panel
    cat > "${sudoers}" <<EOF
# AZERIOID Stack Manager — sudoers (generated by install.sh)
Defaults:${WEB_USER} !requiretty
Defaults:${WEB_USER} umask=0022
${WEB_USER} ALL=(root) NOPASSWD: ${PREFIX}/broker
EOF
    chmod 0440 "${sudoers}"
    visudo -c >/dev/null

    if [[ ! -f /etc/azerioid-panel/broker.json ]]; then
        cat > /etc/azerioid-panel/broker.json <<EOF
{
    "stack": "bootstrap",
    "web_server": "caddy",
    "web_service": "caddy",
    "vhost_format": "caddyfile",
    "paths": {
        "www_root": "${WWW_ROOT:-/data/www}",
        "caddy_confd": "${CADDY_CONFD:-/etc/caddy/conf.d}",
        "caddyfile": "/etc/caddy/Caddyfile",
        "caddy_bin": "/usr/bin/caddy",
        "vhost_dir": "${CADDY_CONFD:-/etc/caddy/conf.d}",
        "vhost_available": "",
        "web_log_dir": "/var/log/caddy",
        "apache_ctl": "",
        "audit_log": "/var/log/azerioid-panel/broker-audit.log",
        "artisan": "${PREFIX}/web/artisan",
        "staging_dir": "/var/lib/azerioid-panel/staging",
        "cron_d": "/etc/cron.d/azerioid-panel",
        "panel_root": "${PREFIX}",
        "registry_components": "${PREFIX}/registry/components",
        "managed_components": "/var/lib/azerioid-panel/managed-components.json",
        "ttyd_bin": "/usr/local/bin/ttyd",
        "terminal_sessions": "/var/lib/azerioid-panel/terminal-sessions.json",
        "terminal_caddy_routes": "/var/lib/azerioid-panel/caddy-terminal-routes.conf"
    },
    "panel_port": ${PANEL_PORT:-3169},
    "terminal_idle_seconds": 1200,
    "terminal_ports": {"min": 35000, "max": 35999},
    "web_user": "${WEB_USER}",
    "panel_runtime": {
        "php_version": "${PANEL_PHP_VERSION}",
        "fpm_socket": "/run/php/azerioid-panel.sock",
        "fpm_pool": "azerioid-panel",
        "queue_unit": "azerioid-panel-queue.service"
    },
    "readonly_vhosts": [],
    "observed_services": []
}
EOF
        chmod 0600 /etc/azerioid-panel/broker.json
    fi

    install -d -m 0755 "${WWW_ROOT:-/data/www}"

    install -d -m 0750 /var/lib/azerioid-panel
    echo "# AZERIOID Stack Manager — no active terminal sessions" > /var/lib/azerioid-panel/caddy-terminal-routes.conf
    chmod 0644 /var/lib/azerioid-panel/caddy-terminal-routes.conf
    touch /var/lib/azerioid-panel/terminal-sessions.json
    chmod 0640 /var/lib/azerioid-panel/terminal-sessions.json
    chown root:root /var/lib/azerioid-panel/terminal-sessions.json /var/lib/azerioid-panel/caddy-terminal-routes.conf

    echo "==> Installing component registry"
    install -d -m 0755 "${PREFIX}/registry/components"
    rsync -a "${ROOT}/registry/" "${PREFIX}/registry/"
    chown -R root:root "${PREFIX}/registry"
    find "${PREFIX}/registry" -type d -exec chmod 0755 {} \;
    find "${PREFIX}/registry" -type f -exec chmod 0644 {} \;
}

install_panel_app() {
    echo "==> Deploying panel web application"
    install -d -m 0750 -o "${WEB_USER}" -g "${WEB_USER}" "${PREFIX}/web"
    rsync -a --delete \
        --exclude '.env' --exclude 'vendor/' --exclude 'node_modules/' \
        --exclude 'tests/' --exclude 'bootstrap/cache/*.php' \
        --exclude 'storage/logs/' --exclude 'storage/framework/cache/' \
        --exclude 'storage/framework/sessions/' --exclude 'storage/framework/views/' \
        --exclude 'storage/framework/tmp/' \
        "${ROOT}/web/" "${PREFIX}/web/"

    install -d -m 0750 -o "${WEB_USER}" -g "${WEB_USER}" "${PREFIX}/web/lib/azerioid-broker"
    rsync -a --delete "${ROOT}/broker/src/" "${PREFIX}/web/lib/azerioid-broker/"

    install -d -m 0770 -o "${WEB_USER}" -g "${WEB_USER}" \
        "${PREFIX}/web/storage" "${PREFIX}/web/storage/logs" \
        "${PREFIX}/web/storage/framework" "${PREFIX}/web/storage/framework/cache" \
        "${PREFIX}/web/storage/framework/cache/data" \
        "${PREFIX}/web/storage/framework/sessions" \
        "${PREFIX}/web/storage/framework/views" \
        "${PREFIX}/web/storage/framework/tmp" \
        "${PREFIX}/web/storage/app" "${PREFIX}/web/bootstrap/cache"

    find "${PREFIX}/web" -type d -exec chmod 0750 {} \;
    find "${PREFIX}/web" -type f -exec chmod 0640 {} \;
    find "${PREFIX}/web/storage" "${PREFIX}/web/bootstrap/cache" -type d -exec chmod 0770 {} \;
    chmod 0750 "${PREFIX}/web" "${PREFIX}/web/public" "${PREFIX}/web/artisan"
    chown -R "${WEB_USER}:${WEB_USER}" "${PREFIX}/web"

    COMPOSER_HOME="$(mktemp -d /tmp/stack-composer.XXXXXX)"
    chown "${WEB_USER}:${WEB_USER}" "${COMPOSER_HOME}"
    export COMPOSER_HOME

    run_as_web "${PHP_BIN} ${COMPOSER_BIN} install --no-dev --optimize-autoloader --no-interaction --no-scripts"
    rm -f "${PREFIX}/web/bootstrap/cache/packages.php" "${PREFIX}/web/bootstrap/cache/services.php"
    run_as_web "${PHP_BIN} artisan package:discover --ansi --no-interaction"
    run_as_web "${PHP_BIN} ${COMPOSER_BIN} dump-autoload -o --no-interaction --no-scripts"
    rm -rf "${COMPOSER_HOME}"

    configure_panel_db

    if ! grep -q '^APP_KEY=base64:' "${PREFIX}/web/.env"; then
        run_as_web "${PHP_BIN} artisan key:generate --force --no-interaction"
    fi
    run_as_web "${PHP_BIN} artisan migrate --force --no-interaction"
    touch "${PREFIX}/web/storage/logs/laravel.log"
    chown "${WEB_USER}:${WEB_USER}" "${PREFIX}/web/storage/logs/laravel.log"

    cat > /etc/cron.d/azerioid-panel <<EOF
# AZERIOID Stack Manager — Laravel scheduler
SHELL=/bin/sh
PATH=/usr/sbin:/usr/bin:/sbin:/bin
* * * * * ${WEB_USER} ${PHP_BIN} ${PREFIX}/web/artisan schedule:run >/dev/null 2>&1
EOF
    chmod 0644 /etc/cron.d/azerioid-panel
}
