#!/usr/bin/env bash
# Panel dedicated PHP-FPM pool at /run/php/azerioid-panel.sock
set -euo pipefail

configure_panel_fpm() {
    echo "==> Configuring panel PHP-FPM pool (PHP ${PANEL_PHP_VERSION})"
    local pool_dir fpm_ini fpm_bin unit
    pool_dir="$(pool_dir)" || { echo "FPM pool directory not found" >&2; return 1; }
    fpm_ini="$(fpm_ini || true)"
    fpm_bin="$(fpm_bin)"
    unit="$(fpm_unit)"

    if [[ -n "${fpm_ini}" && -f "${fpm_ini}" ]] && grep -Eq '^disable_functions[[:space:]]*=' "${fpm_ini}"; then
        if grep -Eq '^disable_functions[[:space:]]*=.*(proc_open|proc_get_status)' "${fpm_ini}"; then
            [[ ! -f "${fpm_ini}.azerioid-panel.bak" ]] && cp -a "${fpm_ini}" "${fpm_ini}.azerioid-panel.bak"
            python3 - "${fpm_ini}" <<'PY'
import pathlib, re, sys
path = pathlib.Path(sys.argv[1])
text = path.read_text()
blocked = {"proc_open", "proc_get_status"}
def repl(match):
    funcs = [f.strip() for f in match.group(1).split(",") if f.strip() and f.strip() not in blocked]
    seen, out = set(), []
    for f in funcs:
        if f not in seen:
            seen.add(f); out.append(f)
    return "disable_functions = " + ",".join(out)
new, n = re.subn(r"^disable_functions\s*=\s*(.*)$", repl, text, count=1, flags=re.M)
if n == 1:
    path.write_text(new)
PY
        fi
    fi

    cat > "${pool_dir}/azerioid-panel.conf" <<EOF
; AZERIOID Stack Manager panel PHP-FPM pool (generated by install.sh)
[azerioid-panel]
user = ${WEB_USER}
group = ${WEB_USER}
listen = /run/php/azerioid-panel.sock
listen.owner = ${WEB_USER}
listen.group = ${WEB_USER}
listen.mode = 0660
pm = ondemand
pm.max_children = 4
pm.process_idle_timeout = 10s
pm.max_requests = 200
php_admin_value[disable_functions] = passthru,exec,shell_exec,system,chroot,chgrp,chown,ini_alter,ini_restore
php_admin_flag[expose_php] = off
php_admin_value[open_basedir] = ${PREFIX}/web:/var/lib/azerioid-panel:/tmp:/dev/urandom:/usr/bin/sudo:/var/log/azerioid-panel
php_admin_value[sys_temp_dir] = ${PREFIX}/web/storage/framework/tmp
php_admin_value[upload_tmp_dir] = ${PREFIX}/web/storage/framework/tmp
php_admin_value[session.save_path] = ${PREFIX}/web/storage/framework/sessions
php_admin_flag[log_errors] = on
php_admin_value[error_log] = /var/log/azerioid-panel/php-fpm.log
EOF
    chmod 0644 "${pool_dir}/azerioid-panel.conf"

    install -d -m 0755 /run/php
    cat > /etc/tmpfiles.d/azerioid-panel.conf <<EOF
d /run/php 0755 ${WEB_USER} ${WEB_USER} -
EOF
    systemd-tmpfiles --create /etc/tmpfiles.d/azerioid-panel.conf >/dev/null 2>&1 || true

    "${fpm_bin}" -t
    install -d -m 0755 "/etc/systemd/system/${unit}.service.d"
    cat > "/etc/systemd/system/${unit}.service.d/azerioid-panel.conf" <<EOF
[Service]
ReadWritePaths=${PREFIX}/web/storage ${PREFIX}/web/bootstrap/cache /var/log/azerioid-panel /var/lib/azerioid-panel
EOF
    systemctl daemon-reload
    systemctl enable --now "${unit}"
    systemctl restart "${unit}"
    write_runtime_json
}
