#!/usr/bin/env bash
# Panel dedicated PHP-FPM pool at /run/php/azerioid-panel.sock
set -euo pipefail

configure_panel_fpm() {
    echo "==> Configuring panel PHP-FPM pool (PHP ${PANEL_PHP_VERSION})"
    local pool_dir fpm_ini fpm_bin unit pool_file
    fpm_ini="$(fpm_ini || true)"
    fpm_bin="$(fpm_bin)"
    unit="$(fpm_unit)"

    if [[ -n "${fpm_ini}" && -f "${fpm_ini}" ]] && grep -Eq '^disable_functions[[:space:]]*=' "${fpm_ini}"; then
        if grep -Eq '^disable_functions[[:space:]]*=.*(proc_open|proc_get_status)' "${fpm_ini}"; then
            [[ ! -f "${fpm_ini}.azerioid-panel.bak" ]] && cp -a "${fpm_ini}" "${fpm_ini}.azerioid-panel.bak"
            python3 - "${fpm_ini}" <<'PY'
import pathlib, re, sys
path = pathlib.Path(sys.argv[1])
text = path.read_text()
blocked = {"proc_open", "proc_get_status"}
def repl(match):
    funcs = [f.strip() for f in match.group(1).split(",") if f.strip() and f.strip() not in blocked]
    seen, out = set(), []
    for f in funcs:
        if f not in seen:
            seen.add(f); out.append(f)
    return "disable_functions = " + ",".join(out)
new, n = re.subn(r"^disable_functions\s*=\s*(.*)$", repl, text, count=1, flags=re.M)
if n == 1:
    path.write_text(new)
PY
        fi
    fi

    if [[ "${DISTRO_FAMILY}" == "el" ]]; then
        install -d -m 0750 -o root -g root /etc/azerioid-panel/php-fpm.d
        pool_file=/etc/azerioid-panel/php-fpm.d/azerioid-panel.conf
    else
        pool_dir="$(pool_dir)" || { echo "FPM pool directory not found" >&2; return 1; }
        pool_file="${pool_dir}/azerioid-panel.conf"
    fi

    cat > "${pool_file}" <<EOF
; AZERIOID Stack Manager panel PHP-FPM pool (generated by install.sh)
[azerioid-panel]
user = ${WEB_USER}
group = ${WEB_USER}
listen = /run/php/azerioid-panel.sock
listen.owner = ${WEB_USER}
listen.group = ${WEB_USER}
listen.mode = 0660
pm = ondemand
pm.max_children = 4
pm.process_idle_timeout = 10s
pm.max_requests = 200
php_admin_value[disable_functions] = passthru,exec,shell_exec,system,chroot,chgrp,chown,ini_alter,ini_restore
php_admin_flag[expose_php] = off
php_admin_value[open_basedir] = ${PREFIX}/web:/var/lib/azerioid-panel:/tmp:/dev/urandom:/usr/bin/sudo:/var/log/azerioid-panel
php_admin_value[sys_temp_dir] = ${PREFIX}/web/storage/framework/tmp
php_admin_value[upload_tmp_dir] = ${PREFIX}/web/storage/framework/tmp
php_admin_value[session.save_path] = ${PREFIX}/web/storage/framework/sessions
php_admin_flag[log_errors] = on
php_admin_value[error_log] = /var/log/azerioid-panel/php-fpm.log
request_terminate_timeout = 60
php_admin_value[max_execution_time] = 60
EOF
    chmod 0644 "${pool_file}"

    install -d -m 0755 /run/php
    cat > /etc/tmpfiles.d/azerioid-panel.conf <<EOF
d /run/php 0755 ${WEB_USER} ${WEB_USER} -
EOF
    systemd-tmpfiles --create /etc/tmpfiles.d/azerioid-panel.conf >/dev/null 2>&1 || true

    configure_site_fpm_timeouts

    if [[ "${DISTRO_FAMILY}" == "el" ]]; then
        configure_panel_fpm_el "${fpm_bin}" "${unit}"
    else
        "${fpm_bin}" -t
        install -d -m 0755 "/etc/systemd/system/${unit}.service.d"
        cat > "/etc/systemd/system/${unit}.service.d/azerioid-panel.conf" <<EOF
[Service]
ReadWritePaths=${PREFIX}/web/storage ${PREFIX}/web/bootstrap/cache /var/log/azerioid-panel /var/lib/azerioid-panel
EOF
        systemctl daemon-reload
        systemctl enable --now "${unit}"
        systemctl restart "${unit}"
    fi
    write_runtime_json
    sync_broker_panel_fpm_unit
}

# EL php-fpm is httpd_exec_t → httpd_t. sudo from that domain cannot start the
# broker (PAM audit_open / unix_chkpwd, often dontaudit). Run the panel pool
# from a bin_t copy of php-fpm so systemd starts unconfined_service_t; leave
# the site www pool on the distro master (httpd_t).
configure_panel_fpm_el() {
    local fpm_bin="$1" stock_unit="$2"
    local panel_fpm="${PREFIX}/sbin/php-fpm"
    install -d -m 0751 -o root -g root "${PREFIX}/sbin"
    install -m 0755 "$(readlink -f "${fpm_bin}")" "${panel_fpm}"
    semanage fcontext -a -t bin_t '/usr/local/lib/azerioid-panel/sbin(/.*)?' 2>/dev/null || true
    restorecon -Rv "${PREFIX}/sbin" >/dev/null 2>&1 || true
    cat > /etc/azerioid-panel/php-fpm.conf <<EOF
; AZERIOID panel PHP-FPM master (generated by install.sh)
[global]
pid = /run/azerioid-panel-php-fpm.pid
error_log = /var/log/azerioid-panel/php-fpm-master.log
daemonize = no
include=/etc/azerioid-panel/php-fpm.d/*.conf
EOF
    chmod 0640 /etc/azerioid-panel/php-fpm.conf
    rm -f /etc/php-fpm.d/azerioid-panel.conf
    "${fpm_bin}" -t --fpm-config /etc/azerioid-panel/php-fpm.conf
    "${fpm_bin}" -t
    cat > /etc/systemd/system/azerioid-panel-php-fpm.service <<EOF
[Unit]
Description=AZERIOID panel PHP-FPM
After=network.target

[Service]
Type=notify
ExecStart=${panel_fpm} --nodaemonize --fpm-config /etc/azerioid-panel/php-fpm.conf
ExecReload=/bin/kill -USR2 \$MAINPID
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF
    chmod 0644 /etc/systemd/system/azerioid-panel-php-fpm.service
    systemctl daemon-reload
    systemctl enable --now "${stock_unit}"
    systemctl restart "${stock_unit}"
    systemctl enable --now azerioid-panel-php-fpm.service
    systemctl restart azerioid-panel-php-fpm.service
}

sync_broker_panel_fpm_unit() {
    local unit
    unit="$(panel_fpm_unit)"
    python3 - "${unit}" <<'PY'
import json, sys
from pathlib import Path
unit = sys.argv[1]
path = Path("/etc/azerioid-panel/broker.json")
if not path.is_file():
    raise SystemExit(0)
data = json.loads(path.read_text())
rt = data.setdefault("panel_runtime", {})
rt["fpm_unit"] = unit
rt.setdefault("fpm_pool", "azerioid-panel")
rt.setdefault("fpm_socket", "/run/php/azerioid-panel.sock")
path.write_text(json.dumps(data, indent=4) + "\n")
path.chmod(0o600)
PY
}

# Shared www pool (site traffic). request_terminate_timeout 0 is unlimited and
# lets one hung script hold a worker forever (and exhaust pm.max_children).
configure_site_fpm_timeouts() {
    python3 - <<'PY'
from pathlib import Path
import glob, re

terminate = "30"
exec_time = "30"
patterns = [
    "/etc/php/*/fpm/pool.d/www.conf",
    "/etc/opt/remi/php*/php-fpm.d/www.conf",
    "/etc/php-fpm.d/www.conf",
]
files = []
for pat in patterns:
    files.extend(glob.glob(pat))
for path in files:
    p = Path(path)
    if not p.is_file():
        continue
    text = p.read_text()
    def set_bare(key, value, src):
        line = f"{key} = {value}"
        pat = rf"(?m)^\s*;?\s*{re.escape(key)}\s*=.*$"
        if re.search(pat, src):
            return re.sub(pat, line, src)
        return src.rstrip() + "\n" + line + "\n"
    def set_admin(key, value, src):
        line = f"php_admin_value[{key}] = {value}"
        pat = rf"(?m)^\s*;?\s*php_admin_value\[{re.escape(key)}\]\s*=.*$"
        if re.search(pat, src):
            return re.sub(pat, line, src)
        return src.rstrip() + "\n" + line + "\n"
    new = set_bare("request_terminate_timeout", terminate, text)
    new = set_admin("max_execution_time", exec_time, new)
    if new != text:
        p.write_text(new)
PY
}
